name: "Test Action"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        service-account: ${{ secrets.SERVICE_ACCOUNT }}
        project-id: ${{ secrets.PROJECT_ID }}
        service-name: ${{ secrets.SERVICE_NAME }}
        debug: true
